version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/galera-do-ti-frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/galera-do-ti-members-lambda"
    schedule:
      interval: "weekly"
